[BUILD] Set max heap size
After the update to gradle 6 the following
exception is thrown:
> java.lang.OutOfMemoryError: Java heap space
(as described in PR #813)

Setting this property fixes the issue.