[INTERNAL][E] Adjust FileActivityConsumerTest to use file encoding
Adjusts the FileActivityConsumerTest to pass a specific file encoding
when creating a file activity. This was done in preparation of an
upcoming change requiring all file activities containing binary content
to also contain a valid encoding.

Introduces UTF-8 as the default chatset to use for the test. Explicitly
uses the charset for the string conversion instead of implicitly using
the JVM default charset.

Restructures the mocking logic to be able to mock internal calls to
IFile.setCharset(String). This is necessary as I am unable to mock the
Eclipse interface IProject which is used in the method.

When trying to mock IProject or its implementations, EasyMock runs ino
a NoClassDefFoundError for org/eclipse/core/runtime/IPluginDescriptor.
The cause of this issue seems to be that the class IPluginDescriptor has
been deprecated and is no longer included in the default Eclipse
artifacts. As a result, I was unable to either mock IProject nor create
an IProject stub implementation. See issue #910.