[STF] 1. move all no exported methods from tablePart, TreePart and ViewPart to class "BasicComponentImp". The reason for the change is that client can flexibly write numerous actions using the basic widgets and such actions based on the basic widgets should be also tested by themselves.
2. write tests for basicCompomentImp

3. initialize the component-variables defined in EclipseComponent using e.g. BasicComponentImp.getInstance() instead of installing them in STFController. 
The reason for the change is that every component can use the methods defined in  other components, which may not be declared in interface.

4. TODO in renameClass in PEVeiwComponentImp
@Andreas, this problem described in TODO of the method "renameClass" in class PEViewComponentImp doesn't exist by me, so i get still the
exception: "button isn't enabled" by performing the codes after TODO. I comment the codes out first, if my change doesn't work by you, please tell me.